### ISSUE TITLE
Implement resid function for chen_reg

### ISSUE THREAD

**Issue by VitorBSP** [AlissonRP/chenreg#8]
The `stats` function `resid()` or `residuals()` is used to extract residuals from objects like `glm`,`lm` or even `coxph(Surv())`.
Reproducible example:
```
df = survival::leukemia
 lm(data = df, time ~ status) |> resid()  |> class()
# [1] "numeric"
glm(data = df, time ~ status) |> resid() |> class()
# [1] "numeric"
survival::coxph(survival::Surv(df$time, df$status)~1) |> resid() |> class()
# [1] "numeric"
chenReg::chen_reg(df, time ~ status) |> resid() |> class()
# [1] "NULL"
```

As you can see all others function implemented  have options to adapt at the `resid` function.

**Comment by AlissonRP** [comment]
Seems ok now
```r
df = survival::leukemia
chenReg::chen_reg(df, time ~ status) |> resid() |> head(3)
#>         [,1]
#> 1 -0.5714376
#> 2 -0.3085323
#> 3 -1.4176646
```

**Comment by VitorBSP** [comment]
> Seems ok now
> 
> ```r
> df = survival::leukemia
> chenReg::chen_reg(df, time ~ status) |> resid() |> head(3)
> #>         [,1]
> #> 1 -0.5714376
> #> 2 -0.3085323
> #> 3 -1.4176646
> ```

thx
